### ISSUE TITLE
Synonym file for Roberta's vocabulary

### ISSUE THREAD

**Issue by Hien-H-Mai** [Raibows/RMLM#1]
Hi, thank for the great work!

I want to implement RMLM for Roberta model. I use Wordnet of NLTK library to reproduce your bert.synonym.json before applying for Roberta's vocabulary, however, I cannot reproduce it. 

Could you release your code to make synonym.json file?

**Comment by Raibows** [comment]
Hi,

I think the BPE tokenizer adopted by Roberta may prohibit you collect meaningful synonyms through NLTK since it is not based on the "word" or "sub-word". A simple solution is to replace the embedding and tokenizer with the one used by BERT. The fine-tuning and joint training will both help fine-tune these new params.

**Comment by Hien-H-Mai** [comment]
Thanks for your suggestions
I will consider using BERT's embedding layer for RoBERTA.
